#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SRC_IMPL_DIR="${PROJECT_DIR}/artifacts/vivado_kv260_impl_refine"
SRC_HWH="${PROJECT_DIR}/build/vivado_kv260_bd/fracnet_kv260.gen/sources_1/bd/design_1/hw_handoff/design_1.hwh"
DEST_DIR="${PROJECT_DIR}/deploy/kv260_200"
DEST_BASENAME="fracnet_kv260_200"

BIT_SRC="${SRC_IMPL_DIR}/design_1_wrapper_refined.bit"
XSA_SRC="${SRC_IMPL_DIR}/fracnet_kv260_refined.xsa"
TIMING_SRC="${SRC_IMPL_DIR}/final_bit_timing_summary.rpt"
UTIL_SRC="${SRC_IMPL_DIR}/post_route_util.rpt"

for path in "${BIT_SRC}" "${SRC_HWH}" "${XSA_SRC}" "${TIMING_SRC}" "${UTIL_SRC}"; do
  if [[ ! -f "${path}" ]]; then
    echo "missing required artifact: ${path}" >&2
    exit 1
  fi
done

mkdir -p "${DEST_DIR}"
cp -f "${BIT_SRC}" "${DEST_DIR}/${DEST_BASENAME}.bit"
cp -f "${SRC_HWH}" "${DEST_DIR}/${DEST_BASENAME}.hwh"
cp -f "${XSA_SRC}" "${DEST_DIR}/${DEST_BASENAME}.xsa"
cp -f "${TIMING_SRC}" "${DEST_DIR}/${DEST_BASENAME}.timing_summary.rpt"
cp -f "${UTIL_SRC}" "${DEST_DIR}/${DEST_BASENAME}.utilization.rpt"
rm -f "${DEST_DIR}/${DEST_BASENAME}.bit.bin"

cat > "${DEST_DIR}/${DEST_BASENAME}.bif" <<BIF
all:
{
  ${DEST_BASENAME}.bit
}
BIF

cat > "${DEST_DIR}/${DEST_BASENAME}.manifest.txt" <<MANIFEST
FracBNN CIFAR-10 KV260 refined 250 MHz bring-up bundle

Generated by:
  scripts/prepare_kv260_deploy_200.sh

Source implementation:
  ${SRC_IMPL_DIR}

Fresh BD handoff:
  ${SRC_HWH}

Files:
  ${DEST_BASENAME}.bit  PYNQ bitstream
  ${DEST_BASENAME}.hwh  PYNQ hardware handoff metadata, renamed to match bitstream basename
  ${DEST_BASENAME}.xsa  Vitis/PetaLinux hardware platform with bitstream
  ${DEST_BASENAME}.bit.bin  fpgautil bitstream generated by bootgen
  ${DEST_BASENAME}.timing_summary.rpt  final timing report copied from refined implementation
  ${DEST_BASENAME}.utilization.rpt  post-route utilization report copied from refined implementation

Clock:
  Current fresh BD run uses PL_CLK_FREQ_MHZ=250.
  Routed clk_pl_0 is 4.000 ns / 250 MHz.
  Latest final bit timing: setup 0 failing endpoints, WNS 0.000 ns, TNS 0.000 ns;
  hold 0 failing endpoints, WHS 0.010 ns, THS 0.000 ns.
  See ${SRC_IMPL_DIR}/final_bit_timing_summary.rpt.

Post-route resources on xck26-sfvc784-2LV-c:
  CLB LUTs: 51,904 / 117,120 = 44.32%
  Block RAM Tile: 119.5 / 144 = 82.99%
  DSPs: 122 / 1,248 = 9.78%

Control:
  FracNet_T_0/s_axi_CTRL base address: 0xA0010000
  image_r address register:  0x10 low, 0x14 high
  output_r address register: 0x1c low, 0x20 high
MANIFEST

if command -v bootgen >/dev/null 2>&1; then
  (
    cd "${DEST_DIR}"
    bootgen -arch zynqmp -image "${DEST_BASENAME}.bif" -process_bitstream bin -w
  )
else
  echo "bootgen not found in PATH; source Vitis settings64.sh and rerun to create ${DEST_BASENAME}.bit.bin" >&2
fi

echo "prepared ${DEST_DIR}:"
ls -lh "${DEST_DIR}/${DEST_BASENAME}.bit" \
       "${DEST_DIR}/${DEST_BASENAME}.bit.bin" \
       "${DEST_DIR}/${DEST_BASENAME}.hwh" \
       "${DEST_DIR}/${DEST_BASENAME}.xsa" \
       "${DEST_DIR}/${DEST_BASENAME}.timing_summary.rpt" \
       "${DEST_DIR}/${DEST_BASENAME}.utilization.rpt" \
       "${DEST_DIR}/${DEST_BASENAME}.manifest.txt"
