open_vcd linear_matmul_debug.vcd
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/linear_out_buf_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/linear_out_buf_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/linear_out_buf_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/linear_out_buf_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/linear_out_buf_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_linear_out_buf_init_fu_2435/linear_out_buf_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_linear_out_buf_init_fu_2435/linear_out_buf_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_linear_out_buf_init_fu_2435/linear_out_buf_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_linear_out_buf_init_fu_2435/linear_out_buf_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/outputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/outputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/outputs_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/outputs_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_write_output_fu_2620/linear_out_buf_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_write_output_fu_2620/linear_out_buf_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_FracNet_T_Pipeline_write_output_fu_2620/linear_out_buf_q0
log_vcd /apatb_FracNet_T_top/RESULT_WVALID
log_vcd /apatb_FracNet_T_top/RESULT_WREADY
log_vcd /apatb_FracNet_T_top/RESULT_WDATA
run all
close_vcd
quit
