open_vcd avgpool_debug.vcd
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_0_0_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_0_0_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_0_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_0_1_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_1_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/inputs_3_15_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_q0
run all
close_vcd
quit
