open_vcd pool_matmul_debug.vcd
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/ap_clk
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/ap_start
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/ap_done
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/ap_start
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/ap_done
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/outputs_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_avgpool_8x8_fu_2525/tmp_s_fu_271_p35
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/pool_out_buf_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/ap_start
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/ap_done
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/inputs_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_matmul_fu_2594/tmp_in_3_fu_733_p3
run all
close_vcd
quit
