open_vcd outbuf_write_debug.vcd

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/ap_CS_fsm

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_ce1
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_q1

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_1_q0

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_16_q0

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/out_buf_0_63_q0

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_ce1
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/residual_0_0_q1

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_0_0_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_0_0_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_0_0_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_0_0_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_0_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/conv_pool_1_0_q0

log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/residual_0_0_address0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/residual_0_0_ce0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/residual_0_0_we0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/residual_0_0_d0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/block_t0_0_q0
log_vcd /apatb_FracNet_T_top/AESL_inst_FracNet_T/grp_pg_conv_bn_loop_fu_957/grp_bn_relu_shortcut_fu_1364/block_t1_0_q0

run all
close_vcd
quit
